# Generated by Django 2.2.5 on 2019-09-10 20:27
import json
from pathlib import Path
from django.db import migrations
from django.contrib.gis.geos import fromstr


def load_data(apps, schema_editor):
    coffee_shop = apps.get_model('coffee', 'CoffeeShop')
    _file = Path(__file__).parents[3] / 'raw_osm.json'

    with _file.open() as f:
        objects = json.load(f)
        for element in objects['elements']:
            try:
                _type = element['type']
                if _type == 'node':
                    tags = element['tags']
                    name = tags.get('name', 'no-name')
                    longitude = element.get('lon', 0)
                    latitude = element.get('lat', 0)

                    # https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
                    SRID = 4326
                    location = fromstr(f'POINT({longitude} {latitude})', srid=SRID)
                    # save to db
                    coffee_shop(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
